package persistance.entities;
// Generated 7 avr. 2021 � 09:42:20 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employe generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYE", schema = "RISBO")
public class Employe implements java.io.Serializable {

	private BigDecimal code;
	private String nom;
	private String prenom;
	private String adresse;
	private Double salaire;

	public Employe() {
	}

	public Employe(BigDecimal code) {
		this.code = code;
	}

	public Employe(BigDecimal code, String nom, String prenom, String adresse, Double salaire) {
		this.code = code;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.salaire = salaire;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCode() {
		return this.code;
	}

	public void setCode(BigDecimal code) {
		this.code = code;
	}

	@Column(name = "NOM", length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 20)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "ADRESSE", length = 20)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "SALAIRE", precision = 126, scale = 0)
	public Double getSalaire() {
		return this.salaire;
	}

	public void setSalaire(Double salaire) {
		this.salaire = salaire;
	}

}
